# Permalinks
permalink:           pretty

# Setup
title:               <YOUR TITLE>
tagline:             <YOUR TAGLINE>
description:         <YOUR DESCRIPTION>
url:                 <YOUR PUBLISHED URL>
paginate:            1
baseurl:             ""
analytics_id:        XXX

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sidhant Gandhi
  url:               http://sidhantgandhi.com
  email:             sidhant.gandhi@gmail.com

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
